services:
  - type: worker
    name: telegram-bot
    env: python
    plan: free
    
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    
    envVars:
      - key: BOT_TOKEN
        scope: run
      - key: OPENROUTER_KEY
        scope: run
      - key: JANICE_ID
        scope: run
      - key: MY_ID
        scope: run
